### ISSUE TITLE
Namespace issue: Error in ranger(formula = reformulate(covariables, response = vv), data = data_imp,  :    could not find function "ranger"

### ISSUE THREAD

**Issue by Deleetdk** [mayer79/outForest#2]
```
> outForest(atmos_cph_num)

Outlier identification by random forests

  Variables to check:		UVIEF, UVIEFerr, UVDEF, UVDEFerr, UVDVF, UVDVFerr, UVDDF, UVDDFerr, ozone
  Variables used to check:	UVIEF, UVIEFerr, UVDEF, UVDEFerr, UVDVF, UVDVFerr, UVDDF, UVDDFerr, ozone

  Checking: UVIEF  Error in ranger(formula = reformulate(covariables, response = vv), data = data_imp,  : 
  could not find function "ranger"
```

`atmos_cph_num` is just some arbitrary dataset. The error here is that https://github.com/mayer79/outForest/blob/master/R/outForest.R#L139 is missing namespace.

**Comment by mayer79** [comment]
What version of the `ranger` package are you using?

**Comment by mayer79** [comment]
Not enough info.

**Comment by Deleetdk** [comment]
Error is unrelated to package versions, you just forgot the namespace on the foreign functions. It's best practice to include these always.

**Comment by mayer79** [comment]
I see. One question: did you install the package from CRAN? There, "ranger" seems to be in the namespace file, but maybe I messed up that file on github...

**Comment by mayer79** [comment]
I tried to fix it, thanks for reporting!

**Comment by mayer79** [comment]
Actually the problem seems to be a wrong install instruction in the readme. Here is the right one using a *subdir*:
```
library(devtools)
install_github("mayer79/outForest", subdir = "release/outforest")
```
Thanks again for reporting.

**Comment by Deleetdk** [comment]
You just need to use e.g. `ranger::ranger()` in your source code. Sometimes it works without, and sometimes it doesn't. Best just to use it always when writing packages.
